// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAR_mDW2jReU2WnYTZpAKTsatVgquAKlg',
    appId: '1:67641965956:web:5e545da2a2034e3c63b1d1',
    messagingSenderId: '67641965956',
    projectId: 'push-notification-b9547',
    authDomain: 'push-notification-b9547.firebaseapp.com',
    storageBucket: 'push-notification-b9547.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApUGLHIRmgUAWkLrKY8hPY_Bbysvu9Xkc',
    appId: '1:67641965956:android:a684cd0ab23c315563b1d1',
    messagingSenderId: '67641965956',
    projectId: 'push-notification-b9547',
    storageBucket: 'push-notification-b9547.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSEoPPaDjjG5nmUzLSRc67p5TSqP1oI60',
    appId: '1:67641965956:ios:818ac16a6438742c63b1d1',
    messagingSenderId: '67641965956',
    projectId: 'push-notification-b9547',
    storageBucket: 'push-notification-b9547.firebasestorage.app',
    iosBundleId: 'com.example.pushnotifcation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSEoPPaDjjG5nmUzLSRc67p5TSqP1oI60',
    appId: '1:67641965956:ios:818ac16a6438742c63b1d1',
    messagingSenderId: '67641965956',
    projectId: 'push-notification-b9547',
    storageBucket: 'push-notification-b9547.firebasestorage.app',
    iosBundleId: 'com.example.pushnotifcation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAR_mDW2jReU2WnYTZpAKTsatVgquAKlg',
    appId: '1:67641965956:web:820e5f178fc16f0663b1d1',
    messagingSenderId: '67641965956',
    projectId: 'push-notification-b9547',
    authDomain: 'push-notification-b9547.firebaseapp.com',
    storageBucket: 'push-notification-b9547.firebasestorage.app',
  );
}
